function [f,dfdx,d2fdx2] = neglogpost_fitF(x,p)

nip   = length(x);
d2fdx2 = zeros(nip,nip);
dx = sqrt(-1)*speye(4)*eps.^2;

for ii = 1:nip
    x = real(x);
    x = x+dx(:,ii);
    p.k1 = exp(x(1));
    p.k2 = exp(x(2));
    p.d1 = exp(x(3));
    p.d2 = exp(x(4));

    [M,D] = Pcycle(p);

    O = [p.Fpa;p.Fpb;p.FpA;p.FpB;p.Fra;p.Frb;p.FrA;p.FrB;p.Fla;p.Flb; ...
         p.FlA;p.FlB];
    
    W = speye(length(O));
    
    %e = [(M(1:2)-O(1:2))/std(O(1:2));(M(3:4)-O(3:4))/std(O(3:4));...
    %    +(M(5:6)-O(5:6))/std(O(5:6));(M(7:8)-O(7:8))/std(O(7:8));...
    %    +(M(9:10)-O(9:10))/std(O(9:10));(M(11:12)-O(11:12))/std(O(11:12))];
    
    e = M-O;
    
    f = 0.5*e.'*W*e;

    
    %figure(1)
    %loglog(M,O,'*')
    %D = [D(1:2,:)/std(O(1:2));D(3:4,:)/std(O(3:4));D(5:6,:)/std(O(5:6));...
    %    D(7:8,:)/std(O(7:8));D(9:10,:)/std(O(9:10));D(11:12,:)/std(O(11:12))];
    dpdx = diag(exp(x));
    dedx = D*dpdx;
    dfdx = e.'*W*dedx;
    
    d2fdx2(ii,:) = imag(dfdx)./eps.^2;
    
end
f = real(f);
dfdx = real(dfdx);
%keyboard
%fname = sprintf('Results_sedi_v1');
%save(fname,'M');

function [M,D] = Pcycle(p)

k1 = p.k1;
k2 = p.k2;
d1 = p.d1;
d2 = p.d2;

Vec = [p.p1;p.p2;p.P1;p.P2;p.pr1;p.pr2;...
     p.PR1;p.PR2;p.Chla;p.Chlb;p.ChlA;p.ChlB];

I = speye(2);
J = [[-(k1+d2)*I,  k2*I,       0*I,   0*I,        0*I,   0*I];...
     [      k1*I, -k2*I,       0*I,   0*I,        0*I,   0*I];...
     [       0*I,  0*I, -(k1+d2)*I,  k2*I,       d1*I,   0*I];...
     [       0*I,  0*I,       k1*I, -k2*I,        0*I,   0*I];...
     [       0*I,  0*I,        0*I,   0*I, -(k1+d1)*I,  k2*I];...
     [       0*I,  0*I,        0*I,   0*I,       k1*I, -k2*I]];

%FJ = mfactor(J);
M = J*Vec;

if nargout >1
    
    dJdk1 = [[ -I,  0*I, 0*I, 0*I, 0*I, 0*I];...
             [  I,  0*I, 0*I, 0*I, 0*I, 0*I];...
             [0*I,  0*I,  -I, 0*I, 0*I, 0*I];...	
             [0*I,  0*I,   I, 0*I, 0*I, 0*I];...
             [0*I,  0*I, 0*I, 0*I,  -I, 0*I];...
             [0*I,  0*I, 0*I, 0*I,   I, 0*I]];
    
    dJdk2 = [[0*I,   I, 0*I, 0*I, 0*I, 0*I];...
             [0*I,  -I, 0*I, 0*I, 0*I, 0*I];...
             [0*I, 0*I, 0*I,   I, 0*I, 0*I];...
             [0*I, 0*I, 0*I,  -I, 0*I, 0*I];...
             [0*I, 0*I, 0*I, 0*I, 0*I,   I];...
             [0*I, 0*I, 0*I, 0*I, 0*I,  -I]];
    
    dJdd1 = [[0*I, 0*I, 0*I, 0*I, 0*I, 0*I];...
             [0*I, 0*I, 0*I, 0*I, 0*I, 0*I];...
             [0*I, 0*I, 0*I, 0*I,   I, 0*I];...
             [0*I, 0*I, 0*I, 0*I, 0*I, 0*I];...
             [0*I, 0*I, 0*I, 0*I,  -I, 0*I];...
             [0*I, 0*I, 0*I, 0*I, 0*I, 0*I]];
    
    dJdd2 = [[ -I, 0*I, 0*I, 0*I, 0*I, 0*I];...
             [0*I, 0*I, 0*I, 0*I, 0*I, 0*I];...
             [0*I, 0*I,  -I, 0*I, 0*I, 0*I];...
             [0*I, 0*I, 0*I, 0*I, 0*I, 0*I];...
             [0*I, 0*I, 0*I, 0*I, 0*I, 0*I];...
             [0*I, 0*I, 0*I, 0*I, 0*I, 0*I]];
    
    
    D = [dJdk1*Vec,...
         dJdk2*Vec,...
         dJdd1*Vec,...
         dJdd2*Vec];
    
end
